### ISSUE TITLE
Integration does not work anymore after compact update to 4.02

### ISSUE THREAD

**Issue by lucaferrucci** [dominikamann/oekofen-pellematic-compact#17]
hello, after the update to version 4.02 of the compact the repository returns an error indicating that the values of the layout are not numeric, downloading the json file from the machine the file is apparently the same.
Is there a solution to avoid losing the configuration in home assistant?
I am attaching the 4.01 and 4.02 files for reference.
Thanks in advance
[4.01.txt](https://github.com/dominikamann/oekofen-pellematic-compact/files/10907791/4.01.txt)
[4.02.txt](https://github.com/dominikamann/oekofen-pellematic-compact/files/10907792/4.02.txt)

**Comment by dominikamann** [comment]
Hi @lucaferrucci,

i checked both files. The new version (4.02) look valid to me. I did not found a difference.
Can you please open the home assistant logs and check if there are more informations provided?

-> Just open http://[your_home_assistant_ip]:8123/config/logs

Thanks!

**Comment by dominikamann** [comment]
Hi @lucaferrucci,
thank you for the error details. Now i found the issue. There is a missing **"** in the JSON. So the JSON format is incorrect.
This is a Bug of the 4.02 version. Can you please report this to Ökofen technical support? They should fix ...
I will look if i can provide a workarround for you ... 

![grafik](https://user-images.githubusercontent.com/29973737/223965995-28803cea-05bf-4117-b93b-9f0eed0ed8a6.png)

**Comment by dominikamann** [comment]
@lucaferrucci: I have implemented a hotfix (until Ökofen fixes their bug) that should fix the faulty JSON ... 
Can you please install it and try it out? 

https://github.com/dominikamann/oekofen-pellematic-compact/releases/tag/v2.1.2 

Thanks!

**Comment by lucaferrucci** [comment]
Hi Dominik, I'd like to give you bad news, but it still doesn't display unknown values, if you want to do some tests I can also give you the credentials of my homeassistant so you can try it directly, no problem
![Schermata 2023-03-13 alle 09 39 30](https://user-images.githubusercontent.com/110548623/224649774-7a1f63b5-586f-4038-b889-de8acb3bdaaf.jpg)
![Pellematic](https://user-images.githubusercontent.com/110548623/224649875-9d1e6041-4e14-4204-b57c-e59830d9184c.jpg)

**Comment by dominikamann** [comment]
Hi,

which version did you installed?

**Comment by lucaferrucci** [comment]
4.02

Hello, good morning, I wrote to you that the head of Oekofen Italy replied?  he forwarded our report to the developers department


Grazie Luca.
Ho mandato al ufficio programmazione.
 
Distinti saluti
Schnarf Michael
 
ÖkoFEN Italia srl
Il riscaldamento a pellet
39025 Naturno | Via Peter Mitterhofer 23 | Italy
tel: +39 0473-667867
email: ***@***.*** ***@***.***>  web: www.oekofen.it <http://www.oekofen.it/>

**Comment by dominikamann** [comment]
Perfect! I meant, which version of my integration do you have installed? I have released 2 versions yesterday for your problem. v2.1.3 is the right one for you.

https://github.com/dominikamann/oekofen-pellematic-compact/releases/tag/v2.1.3

**Comment by lucaferrucci** [comment]
Hello good morning, sorry, I thought you meant the oekofen version, I ran the latest update proposed by hass, I just replaced the _init file and restarted hass, but nothing changed, always the same error

**Comment by dominikamann** [comment]
Ok can you please provide the error logs from HA again? Thanks

**Comment by lucaferrucci** [comment]
Dettagli registro (ERRORE)



Questo errore ha avuto origine da un'integrazione personalizzata.
Logger: custom_components.oekofen_pellematic_compact
Source: custom_components/oekofen_pellematic_compact/__init__.py:160 
Integration: Ökofen Pellematic Compact (documentation <https://github.com/dominikamann/oekofen-pellematic-compact>, issues <https://github.com/dominikamann/oekofen-pellematic-compact/issues>) 
First occurred: 07:21:31 (754 occurrences) 
Last logged: 11:32:36

Error reading pellematic data
Traceback (most recent call last):
  File "/config/custom_components/oekofen_pellematic_compact/__init__.py", line 134, in async_refresh_api_data
    update_result = await self.fetch_pellematic_data()
  File "/config/custom_components/oekofen_pellematic_compact/__init__.py", line 150, in fetch_pellematic_data
    result = await self._hass.async_add_executor_job(fetch_data, self._host)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/oekofen_pellematic_compact/__init__.py", line 160, in fetch_data
    result = json.loads(response)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 59 column 17 (char 2024)

**Comment by dominikamann** [comment]
That is really strange I double checked it. With the latest release it should work. Did you restarted HA after Update?

**Comment by dominikamann** [comment]
@lucaferrucci can you please check  in HACS if you use the latest version (v2.1.4).

Go to HACS->Integrations->Ökofen Pellematic Compact

Thanks. 

![image](https://user-images.githubusercontent.com/29973737/226140435-22cb999e-2dfb-4ab9-abfb-76cf8158b786.png)

**Comment by lucaferrucci** [comment]
hi Domink, in fact I don't have the latest version, but I have to update it manually, Hass doesn't offer it to me

**Comment by lucaferrucci** [comment]
Repository updated but i’ve some error

Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.oekofen_pellematic_compact
Source: custom_components/oekofen_pellematic_compact/__init__.py:169 
Integration: Ökofen Pellematic Compact (documentation, issues) 
First occurred: 10:11:23 (89 occurrences) 
Last logged: 10:41:04

Error reading pellematic data
Traceback (most recent call last):
  File "/config/custom_components/oekofen_pellematic_compact/__init__.py", line 134, in async_refresh_api_data
    update_result = await self.fetch_pellematic_data()
  File "/config/custom_components/oekofen_pellematic_compact/__init__.py", line 150, in fetch_pellematic_data
    result = await self._hass.async_add_executor_job(fetch_data, self._host)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/oekofen_pellematic_compact/__init__.py", line 169, in fetch_data
    result = json.loads(str_response)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 59 column 17 (char 2050)

**Comment by dominikamann** [comment]
@lucaferrucci sometimes the update is only visible if you open HACS. Go into Integration, select a integration. If you now open HACS again the update is visible. 

Thank you for your feedback. I found the issue. I released a new version some minutes ago. Please install & try again.

**Comment by lucaferrucci** [comment]
NICE, is all OK!!!
SuperDominik!!!

**Comment by dominikamann** [comment]
Perfect i'm happy to hear that 👍
